### ISSUE TITLE
Error: AbstractSparseMatrixCSC is not found

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/LuxurySparse.jl#37]
currently not working on 1.5

**Comment by jheinen** [comment]
I'm running into the same problem with Julia 1.4.0.

Changing the [version test](https://github.com/QuantumBFS/LuxurySparse.jl/blob/976989bb6bacf41e06ed5d43cd80daa255fb8a02/src/SSparseMatrixCSC.jl#L3) fixes the problem, but is probably not the solution.
```
export SSparseMatrixCSC

@static if VERSION < v"1.4.0" # v"1.5.0" - monkey patch for Julia 1.4.0
...
```

**Comment by Roger-luo** [comment]
fixed
