### ISSUE TITLE
show fails for SSparseMatrixCSC

### ISSUE THREAD

**Issue by agrimsm** [QuantumBFS/LuxurySparse.jl#73]
The following example lightly adapted from the README
```
using SparseArrays
using LuxurySparse

pm = pmrand(7)

Spm = pm |> SparseMatrixCSC

spm = Spm |> staticize

@show spm
```
fails with a `MethodError: no method matching _checkbuffers(::SSparseMatrixCSC{Float64, Int64, 7, 8})`. The `_checkbuffers` method is called from `Base.array_summary` .

**Comment by GiggleLiu** [comment]
Thank your for the bug report. It will be fixed by #74 .
